/**
 * <copyright>
 * </copyright>
 *
 * $Id: LogValidator.java,v 1.1 2007/07/30 21:12:09 delmyers Exp $
 */
package net.sourceforge.tagsea.logging.validation;

import java.util.Date;

/**
 * A sample validator interface for {@link net.sourceforge.tagsea.logging.Log}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LogValidator {
	boolean validate();

	boolean validateUid(int value);
	boolean validateDate(Date value);
	boolean validateUname(String value);
	boolean validateCountry(String value);
	boolean validateLanguage(String value);
	boolean validateSession(int value);
}
