package net.sourceforge.tagsea.tasks;

import net.sourceforge.tagsea.resources.ResourceWaypointPlugin;
import net.sourceforge.tagsea.resources.ResourceWaypointPreferences;

import org.eclipse.core.runtime.preferences.AbstractPreferenceInitializer;

public class TaskWaypointPreferences extends AbstractPreferenceInitializer {
	/**
	 * Represents the filter types for the resource waypoints custom waypoint filter.
	 * @author Del Myers
	 *
	 */
	
	public static final String FILTER_PREFERENCE_KEY = ResourceWaypointPreferences.FILTER_PREFERENCE_KEY;
	public static final String LINK_TO_RESOURCES_KEY = "linkeToResources";
	public static final String FILTER_ANY = ResourceWaypointPreferences.FILTER_ANY;
	public static final String FILTER_SELECTED = ResourceWaypointPreferences.FILTER_SELECTED;
	public static final String FILTER_PROJECT = ResourceWaypointPreferences.FILTER_PROJECT;
	public static final String FILTER_CHILDREN = ResourceWaypointPreferences.FILTER_CHILDREN;
	public static final String AUTO_GENERATED_MATCH_KEY = "autoGeneratedMatchKey";
	public static final String AUTO_GENERATED_KEY = "autoGeneratedKey";
	
	
	public TaskWaypointPreferences() {
	}

	@Override
	public void initializeDefaultPreferences() {
		TaskWaypointPlugin.getDefault().getPreferenceStore().setDefault(FILTER_PREFERENCE_KEY, FILTER_ANY);
		TaskWaypointPlugin.getDefault().getPreferenceStore().setDefault(LINK_TO_RESOURCES_KEY, true);
		TaskWaypointPlugin.getDefault().getPreferenceStore().setDefault(AUTO_GENERATED_KEY, false);
		TaskWaypointPlugin.getDefault().getPreferenceStore().setDefault(AUTO_GENERATED_MATCH_KEY, "Auto-generated");
	}
	
	public static String getCurrentFilterType() {
		if (!isFilterLinkedToResources()) {
			return TaskWaypointPlugin.getDefault().getPreferenceStore().getString(FILTER_PREFERENCE_KEY);
		}
		return ResourceWaypointPlugin.getDefault().getPreferenceStore().getString(FILTER_PREFERENCE_KEY);
	}
	
	public static boolean isFilterLinkedToResources() {
		return TaskWaypointPlugin.getDefault().getPreferenceStore().getBoolean(LINK_TO_RESOURCES_KEY);
	}

	/**
	 * @return
	 */
	public static String getAutoGeneratedMatchText() {
		return TaskWaypointPlugin.getDefault().getPreferenceStore().getString(AUTO_GENERATED_MATCH_KEY);
	}
	
	public static void setAutoGeneratedMatchText(String text) {
		TaskWaypointPlugin.getDefault().getPreferenceStore().putValue(AUTO_GENERATED_MATCH_KEY, text);
	}

	/**
	 * @return
	 */
	public static boolean isFilterAutoGenerated() {
		return TaskWaypointPlugin.getDefault().getPreferenceStore().getBoolean(AUTO_GENERATED_KEY);
	}
	
	public static void setFilterAutoGenerated(boolean filter) {
		TaskWaypointPlugin.getDefault().getPreferenceStore().setValue(AUTO_GENERATED_KEY, filter);
	}

}
